//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPaginaryDetalle.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ContextoHospital : DbContext
    {
        public ContextoHospital()
            : base("name=ContextoHospital")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DOCTOR> DOCTOR { get; set; }
        public DbSet<HOSPITAL> HOSPITAL { get; set; }
    
        public virtual ObjectResult<PAGINARHOSPITAL_Result> PAGINARHOSPITAL(Nullable<int> pOSICION)
        {
            var pOSICIONParameter = pOSICION.HasValue ?
                new ObjectParameter("POSICION", pOSICION) :
                new ObjectParameter("POSICION", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PAGINARHOSPITAL_Result>("PAGINARHOSPITAL", pOSICIONParameter);
        }
    }
}
